name: Update Packagist

on:
    push:
        branches:
            - main
        tags:
            - 'v*'

jobs:
    update-packagist:
        runs-on: ubuntu-latest
        steps:
            - name: Trigger Packagist Update
              env:
                  PACKAGIST_USERNAME: ${{ secrets.PACKAGIST_USERNAME }}
                  PACKAGIST_API_TOKEN: ${{ secrets.PACKAGIST_API_TOKEN }}
                  REPOSITORY: https://github.com/${{ github.repository }}
              run: |
                  curl -X POST \
                    -H "Content-Type: application/json" \
                    "https://packagist.org/api/update-package?username=$PACKAGIST_USERNAME&apiToken=$PACKAGIST_API_TOKEN" \
                    -d "{\"repository\":\"$REPOSITORY\"}"
